spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default: "http://${eureka.instance.hostname}:${server.port}/eureka/"
